### ISSUE TITLE
release the current version on pypi

### ISSUE THREAD

**Issue by jpoullet2000** [ContinuumIO/intake-spark#7]
Hi. Thx for the package. Is it planned to release the current version to pypi? It seems that the one on pypi is a bit outdated. Thx a lot.

**Comment by martindurant** [comment]
Yes, fair enough, that would be reasonable. It would be nice to pair that with changing the CI to github-actions, but we'll see. Please ping me next week if I haven't done anything.

**Comment by martindurant** [comment]
done
